// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADNtWTcJcGY1M1gZsoVP1nI0WfL8i5pGU',
    appId: '1:559788872875:web:0af3d936be0987bcc7d3ee',
    messagingSenderId: '559788872875',
    projectId: 'tasty-643c3',
    authDomain: 'tasty-643c3.firebaseapp.com',
    storageBucket: 'tasty-643c3.appspot.com',
    measurementId: 'G-LN98GLZ7MQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6oyo1LWoIw1ZJAEwoF-Rau017uBxuHeI',
    appId: '1:559788872875:android:90698ab543a42226c7d3ee',
    messagingSenderId: '559788872875',
    projectId: 'tasty-643c3',
    storageBucket: 'tasty-643c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfzr2CNH8WRGzP6PlQvIr_OShmEvI9QJ8',
    appId: '1:559788872875:ios:11fb030a188ecf60c7d3ee',
    messagingSenderId: '559788872875',
    projectId: 'tasty-643c3',
    storageBucket: 'tasty-643c3.appspot.com',
    iosBundleId: 'com.example.foode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfzr2CNH8WRGzP6PlQvIr_OShmEvI9QJ8',
    appId: '1:559788872875:ios:11fb030a188ecf60c7d3ee',
    messagingSenderId: '559788872875',
    projectId: 'tasty-643c3',
    storageBucket: 'tasty-643c3.appspot.com',
    iosBundleId: 'com.example.foode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADNtWTcJcGY1M1gZsoVP1nI0WfL8i5pGU',
    appId: '1:559788872875:web:c749893a25e450aec7d3ee',
    messagingSenderId: '559788872875',
    projectId: 'tasty-643c3',
    authDomain: 'tasty-643c3.firebaseapp.com',
    storageBucket: 'tasty-643c3.appspot.com',
    measurementId: 'G-ETL4MJ2NSW',
  );
}
